### PR TITLE
change table selector as the default table does not exist always

### PR DESCRIPTION
**Pull request by fib1d**
Hi,
great work! Unfortunately in my environment the table which is used to display the commandline does not exist. I changed it to the welcome_2 table which is the most upper one.
Please check if your setup contains this table as well. Maybe a different approach such as an alert box would be better then.

Thanks for the great script and the convenient setup 👍

### CODE REVIEW

**Comment by zouppen** [comment]
Thanks! I'll give it a try tomorrow morning :-)

**Comment by zouppen** [comment]
It worked for me but was looking a bit glitchy. How about this location? Does it work on your page? https://github.com/zouppen/pulse-openconnect-helper/tree/outside_table

**Comment by fib1d** [comment]
perfect! d3237d8688da51d5e02742c062ead19c5dbdf992 is indeed better 😃

**Comment by zouppen** [comment]
Great! :-) Merged d3237d8688da51d5e02742c062ead19c5dbdf992 to master.

**Pull request closed without merging**
